Switch match secret repo from "match-secrets" to "trio-match-secrets"

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -79,22 +79,22 @@ jobs:
           set -o pipefail
 
           # If a Match-Secrets repository does not exist, attempt to create one.
-          if ! visibility=$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase'); then
-            echo "A '${{ github.repository_owner }}/Match-Secrets' repository could not be found using the GH_PAT secret. Attempting to create one..."
+          if ! visibility=$(gh repo view ${{ github.repository_owner }}/Trio-Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase'); then
+            echo "A '${{ github.repository_owner }}/Trio-Match-Secrets' repository could not be found using the GH_PAT secret. Attempting to create one..."
             
             # Create a private Match-Secrets repository and verify that it exists and that it is private.
-            if gh repo create ${{ github.repository_owner }}/Match-Secrets --private >/dev/null && [ "$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase')" == "private" ]; then
-              echo "Created a private '${{ github.repository_owner }}/Match-Secrets' repository."
+            if gh repo create ${{ github.repository_owner }}/Trio-Match-Secrets --private >/dev/null && [ "$(gh repo view ${{ github.repository_owner }}/Trio-Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase')" == "private" ]; then
+              echo "Created a private '${{ github.repository_owner }}/Trio-Match-Secrets' repository."
             else
               failed=true
-              echo "::error::Unable to create a private '${{ github.repository_owner }}/Match-Secrets' repository. Create a private 'Match-Secrets' repository manually and try again. If a private 'Match-Secrets' repository already exists, verify that the token permissions of the GH_PAT are set correctly (or update them) at https://github.com/settings/tokens and try again."
+              echo "::error::Unable to create a private '${{ github.repository_owner }}/Trio-Match-Secrets' repository. Create a private 'Match-Secrets' repository manually and try again. If a private 'Match-Secrets' repository already exists, verify that the token permissions of the GH_PAT are set correctly (or update them) at https://github.com/settings/tokens and try again."
             fi
           # Otherwise, if a Match-Secrets repository exists, but it is public, cause validation to fail.
           elif [[ "$visibility" == "public" ]]; then
             failed=true
-            echo "::error::A '${{ github.repository_owner }}/Match-Secrets' repository was found, but it is public. Change the repository visibility to private (or delete it) and try again. If necessary, a private repository will be created for you."
+            echo "::error::A '${{ github.repository_owner }}/Trio-Match-Secrets' repository was found, but it is public. Change the repository visibility to private (or delete it) and try again. If necessary, a private repository will be created for you."
           else
-            echo "Found a private '${{ github.repository_owner }}/Match-Secrets' repository to use."
+            echo "Found a private '${{ github.repository_owner }}/Trio-Match-Secrets' repository to use."
           fi
 
           # Exit unsuccessfully if secret validation failed.
